# Generated by Django 3.0.7 on 2020-06-09 15:51

from django.db import migrations, models
import weather.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6, validators=[weather.validators.validate_latitude])),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7, validators=[weather.validators.validate_longitude])),
                ('result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6, validators=[weather.validators.validate_latitude])),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7, validators=[weather.validators.validate_longitude])),
            ],
            options={
                'unique_together': {('name', 'latitude', 'longitude')},
            },
        ),
    ]
