# Generated by Django 3.0.7 on 2020-06-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_history_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
